# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3040b62bd9f939fa83c15377eb5323807b2d75c8210335a2574ace97a604f7a278a06fdd39f713879127dfc85951ea4dbfc454c4e3c0e01a9bac6b2f4f914d68

test:
  secret_key_base: 0aedf0b56f7b417f1b602120d6f5d93390ad0a9f3d2ca351e2b64a650ce4d685d3d63c1b15df1087cacf76196e5286a274260cc48b77ce7c362fa542480c13aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
